name: On-Join-Dynmap-Url
version: '1.7-SNAPSHOT'
main: dev.bokukoha.onJoinDynmapURL.OnJoinDynmapURL
api-version: '1.21'
commands:
  dynURL:
    description: Toggles sending Dynmap URL on player join.
permission: OnJoinDynmapURL.commands.dynurl
permissions:
  OnJoinDynmapURL.*:
    children:
      OnJoinDynmapURL: true
    description: all commands.
    default: op
  OnJoinDynmapURL.commands:
    default: op
    children:
      OnJoinDynmapURL.commands.dynurl: true
      OnJoinDynmapURL.commands.default: true
  OnJoinDynmapUrl.commands.dynurl:
    description: only dynURL personal command.
    default: false
  OnJoinDynmapURL.commands.default:
    description: access to global sending URL settings.
    default: false
