name: On-Join-Dynmap-Url
version: '1.0-SNAPSHOT'
main: onJoinDynmapUrl.OnJoinDynmapUrl
api-version: '1.21'
commands:
  dynurl:
    description: Toggles sending Dynmap URL on player join.
permission: OnJoinDynmapUrl.commands.dynurl
permissions:
  OnJoinDynmapUrl.*:
    children:
      OnJoinDynmapUrl: true
    description: all commands.
    default: op
  OnJoinDynmapUrl.commands:
    default: op
    children:
      OnJoinDynmapUrl.commands.dynurl: true
  OnJoinDynmapUrl.commands.dynurl:
    description: only dynurl command.
    default: false
